
ehome:
  port: 9000
  # 公网ip
  pu-ip: 192.168.2.242
  # 内网ip
  in-ip: 192.168.2.242
  # ehome5.0秘钥123456
  secret-key: 123456
  # cms服务端口
  cms-port: 7660
  # 流媒体预览端口
  sms-preview-port: 7662
  # 流媒体回放端口
  sms-back-port: 7665
  # ss服务端口
  ss-port: 6011
  # ss文件保存路径
  ss-filepath: D:/zhny/monitor/
  # 回放视频存储地址
  playBack-videoPath: E:/zhny/playBack_video/
  Alarm:
    # Alarm监听端口
    Alarm-Tcp-port: 7663
    Alarm-Udp-port: 7664
    Alarm-Server-type: 2
    EventInfoPrintType: file